services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anti-fraude

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
   
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: [zookeeper]
   
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ulimits:
      core: -1
    ports:
      - 9092:9092

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      KAFKA_HOST: "localhost"        # Nombre del servicio Kafka
      KAFKA_PORT: "29092"        # Puerto interno de Kafka
      KAFKA_BROKERS: "kafka:29092" # Lista de brokers Kafka
      POSTGRES_HOST: "postgres"   # Host para PostgreSQL
      POSTGRES_USER: "postgres"    # Usuario de PostgreSQL
      POSTGRES_PASSWORD: "postgres" # Contraseña de PostgreSQL
      POSTGRES_DB: "anti-fraude"   # Base de datos a usar
    depends_on:
      - kafka
      - postgres